version: '3.1'

services:
  db:
    image: postgres:14.3
    container_name: "jdbc-cod3r-course"
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432"